polyfill documentation.  Also don't spin in an infinite loop if the nc command isn't found.

diff --git a/s/runtests b/s/runtests
--- a/s/runtests
+++ b/s/runtests
@@ -36,6 +36,12 @@ function launch_server() {
 
     SERVER_PID="$!"
     cd - > /dev/null
+    type -P nc 2>&1 >/dev/null || {
+        echo "nc command not found"
+        echo "If using Cygwin, please install the nc package."
+        fail
+    }
+        
     while true; do
         nc -n 127.0.0.1 8001 < /dev/null
         if [ $? -eq 0 ]; then
